In [2]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


#scaler tensor:


In [3]:
scaler=torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
scaler.item()

7

In [6]:
#vecotr:
vector=torch.tensor([1,2,3])

In [7]:
vector.shape

torch.Size([3])

#Matrix:


In [8]:
Matrix=torch.tensor([[1,2],[3,4]])

In [9]:
Matrix.shape

torch.Size([2, 2])

In [10]:
Matrix.ndim

2

In [11]:
Matrix[0]

tensor([1, 2])

In [12]:
Matrix[0][0]

tensor(1)

#tensor

In [13]:
  Tensor=torch.tensor([[[1,2],[3,4]]])

In [14]:
Tensor.shape

torch.Size([1, 2, 2])

In [15]:
Tensor.ndim

3

#random tensors:


In [16]:
randomTensor=torch.rand(3,4)

In [17]:
randomTensor

tensor([[0.4151, 0.7463, 0.2483, 0.2884],
        [0.5678, 0.3927, 0.5637, 0.1131],
        [0.4630, 0.2749, 0.6473, 0.1179]])

In [18]:
randomTensor.ndim

2

In [19]:
zero_tensor=torch.zeros(size=(3,3))

In [20]:
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
ones=torch.ones(size=(2,2))

In [22]:
ones

tensor([[1., 1.],
        [1., 1.]])

In [23]:
##making tensor range and tensor looks like another tensor



```
##making tensor range and tensor looks like another tensor```#



In [24]:
range_tensor=torch.arange(0,10)

In [25]:
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
like_tensor=torch.zeros_like(range_tensor)

In [27]:
like_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
#tensor data types

#tensor data types

In [29]:
float_32_tensor=torch.tensor([3.0,2.0,4.000],requires_grad=False,device=None)


In [30]:
float_32_tensor

tensor([3., 2., 4.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_32_tensor.device

device(type='cpu')

##manipulating Tensors

In [33]:
tensor_1=torch.tensor([1,2,3])

In [34]:
tensor_1*tensor_1

tensor([1, 4, 9])

In [35]:
 torch.matmul(tensor_1,tensor_1)

tensor(14)

In [36]:
t2=tensor_1.T

<ipython-input-36-100723eccbc6>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3277.)
  t2=tensor_1.T


In [37]:
torch.matmul(tensor_1,t2)

tensor(14)

##maen max sum of 

In [38]:
v=torch.tensor([1,2,3,4,5])

In [39]:
v.max()

tensor(5)

In [40]:
v.min()

tensor(1)

In [41]:
v.sum()

tensor(15)

In [42]:
torch.mean(v.type(torch.float32))

tensor(3.)

## finding the index of the max and min

In [43]:
v.argmin()

tensor(0)

In [44]:
v.argmax()

tensor(4)

##reshaping , viewing and stacking tensors

In [45]:
tensor=torch.tensor([2,3,4,5,6,7,8,9,1,2,3,4])

In [46]:
tensor=tensor.reshape(3,4)

In [47]:
tensor.view(4,3)

tensor([[2, 3, 4],
        [5, 6, 7],
        [8, 9, 1],
        [2, 3, 4]])

In [48]:
tensor

tensor([[2, 3, 4, 5],
        [6, 7, 8, 9],
        [1, 2, 3, 4]])

In [49]:
tensor2=torch.tensor([2,3,4,5,6,7,8,15,3,2,5,3])

In [50]:
tensor2=tensor2.reshape(3,4)

In [51]:
tensor3=torch.stack([v,v,v,v,v,v],axis=0)

In [52]:
tensor3

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

##squeezing and unsquezzing

In [53]:
#torch.squeeze() -> removes all single dimention from a tensor

In [54]:
x=torch.ones(3,1,4,1,5,6)


In [55]:
y=torch.squeeze(x)

In [56]:
y.shape

torch.Size([3, 4, 5, 6])

In [57]:
#torch.unsqueeze() -> add a 1 demention to the tensor

In [58]:
z=torch.unsqueeze(y,dim=0)

In [59]:
z.shape

torch.Size([1, 3, 4, 5, 6])

In [60]:
# torch.permute() -> re arrange the dimentions of the target tensor in a specific order

In [61]:
z=torch.permute(x,([1,2,0,3,5,4]))

In [62]:
z.shape

torch.Size([1, 4, 3, 1, 6, 5])

##indexing "selecting data from tensors"

In [63]:
x=torch.arange(0,12).reshape(1,3,4)

In [64]:
x.shape

torch.Size([1, 3, 4])

In [65]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

In [66]:
x[0][0][0]

tensor(0)

In [67]:
x[:,0]

tensor([[0, 1, 2, 3]])

## Pytorch Reducibility  

In [68]:
# how neural network learns 

In [69]:
# we start with random numbers in a tensor then update them  to make better represtentation of the data

In [70]:
# we want to take the properity randomeness from random

In [71]:
#we achieve this by using Random seed 

In [72]:
#every time you run this cell , you get different answers:
torch.rand(3,3)

tensor([[0.5568, 0.8840, 0.5811],
        [0.2226, 0.4500, 0.8817],
        [0.0611, 0.8977, 0.0421]])

In [73]:
# let us use reproducable random tensor

In [74]:
#set the random seed
torch.manual_seed(42)
rand_tensor1=torch.rand(3,4)
torch.manual_seed(42)
rand_tensor2=torch.rand(3,4)

In [75]:
rand_tensor1

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [76]:
rand_tensor2

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

## tensors on GPU

In [77]:
# make sure to change run time mode to GPU

In [78]:
!nvidia-smi

Tue Dec 20 17:33:07 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P0    26W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [79]:
torch.cuda.is_available()

True

In [81]:
device='cuda' if torch.cuda.is_available( ) else "cpu"

In [82]:
device

'cuda'

In [83]:
#count number of gpu

In [84]:
torch.cuda.device_count()

1